### ISSUE TITLE
测试发现Tcpserver运行过程中会崩溃

### ISSUE THREAD

**Issue by weibw-720** [ZLMediaKit/ZLToolKit#197]
以下是在ubuntu 20.04中运行的gdb堆栈信息
![微信截图_20231222223249](https://github.com/ZLMediaKit/ZLToolKit/assets/58965236/9061e2ff-67db-48e2-90e9-dca6102b5e26)

**Comment by weibw-720** [comment]
感觉和我这边的多线程有关，我看了好多了coredump，每次崩溃位置不一样，包括之前有个人提的issue遇到那个写日志崩溃的情况我也遇到了
我重新整理了我这边代码后问题目前还没有出现

**Comment by weibw-720** [comment]
另外我发现在windows下用MINGW编译器有个地方编译报错，解决了报错后，跑个测试回显tcp_server对cpu的使用都很高能达到20%以上，我的测试环境CPU是i7-12700。MSVC编译器的一切正常

**Comment by weibw-720** [comment]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f9e5bc08859 in __GI_abort () at abort.c:79
#2  0x00007f9e5bc7326e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f9e5bd9d298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f9e5bc7b2fc in malloc_printerr (str=str@entry=0x7f9e5bd9b4c1 "free(): invalid pointer") at malloc.c:5347
#4  0x00007f9e5bc7cb2c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4173
#5  0x00007f9e5c452a32 in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<toolkit::BufferSendMsg, std::allocator<toolkit::BufferSendMsg>, (__gnu_cxx::_Lock_policy)2> >::deallocate (this=0x7f9e5abd941f, __p=0x7f9e5000bb50) at /usr/include/c++/5/ext/new_allocator.h:110
#6  0x00007f9e5c4526ff in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<toolkit::BufferSendMsg, std::allocator<toolkit::BufferSendMsg>, (__gnu_cxx::_Lock_policy)2> > >::deallocate (__a=..., __p=0x7f9e5000bb50, __n=1) at /usr/include/c++/5/bits/alloc_traits.h:517
#7  0x00007f9e5c452226 in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<toolkit::BufferSendMsg, std::allocator<toolkit::BufferSendMsg>, (__gnu_cxx::_Lock_policy)2> > >::~__allocated_ptr (this=0x7f9e5abd9420, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/allocated_ptr.h:72
#8  0x00007f9e5c452f06 in std::_Sp_counted_ptr_inplace<toolkit::BufferSendMsg, std::allocator<toolkit::BufferSendMsg>, (__gnu_cxx::_Lock_policy)2>::_M_destroy (
    this=0x7f9e5000bb50) at /usr/include/c++/5/bits/shared_ptr_base.h:539
#9  0x00000000004318d4 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f9e5000bb50) at /usr/include/c++/5/bits/shared_ptr_base.h:167
#10 0x0000000000430285 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f9e500095e8, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/shared_ptr_base.h:659
#11 0x00007f9e5c4449b6 in std::__shared_ptr<toolkit::BufferList, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f9e500095e0, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/shared_ptr_base.h:925
#12 0x00007f9e5c4449d2 in std::shared_ptr<toolkit::BufferList>::~shared_ptr (this=0x7f9e500095e0, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/shared_ptr.h:93
#13 0x00007f9e5c4485c2 in std::_List_node<std::shared_ptr<toolkit::BufferList> >::~_List_node (this=0x7f9e500095d0, __in_chrg=<optimized out>)
    at /usr/include/c++/5/bits/stl_list.h:106
#14 0x00007f9e5c4485e2 in __gnu_cxx::new_allocator<std::_List_node<std::shared_ptr<toolkit::BufferList> > >::destroy<std::_List_node<std::shared_ptr<toolkit::BufferList> > > (this=0x7f9e5abd95d0, __p=0x7f9e500095d0) at /usr/include/c++/5/ext/new_allocator.h:124
#15 0x00007f9e5c447f0d in std::__cxx11::list<std::shared_ptr<toolkit::BufferList>, std::allocator<std::shared_ptr<toolkit::BufferList> > >::_M_erase (
    this=0x7f9e5abd95d0, Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer':
__position=) at /usr/include/c++/5/bits/stl_list.h:1777
#16 0x00007f9e5c4468a6 in std::__cxx11::list<std::shared_ptr<toolkit::BufferList>, std::allocator<std::shared_ptr<toolkit::BufferList> > >::pop_front (
    this=0x7f9e5abd95d0) at /usr/include/c++/5/bits/stl_list.h:1075
#17 0x00007f9e5c43aaf7 in toolkit::Socket::flushData (this=0x7f9e440010f0, sock=std::shared_ptr<class toolkit::SockNum> (use count 3, weak count 0) = {...},
    poller_thread=false) at /Network/Socket.cpp:727
#18 0x00007f9e5c438a61 in toolkit::Socket::flushAll (this=0x7f9e440010f0) at /Network/Socket.cpp:403
#19 0x00007f9e5c438953 in toolkit::Socket::send_l (this=0x7f9e440010f0, buf=std::shared_ptr<class toolkit::Buffer> (empty) = {...}, is_buf_sock=false,
    try_flush=true) at /Network/Socket.cpp:386
#20 0x00007f9e5c438782 in toolkit::Socket::send (this=0x7f9e440010f0, buf=std::shared_ptr<class toolkit::Buffer> (empty) = {...}, addr=0x0, addr_len=0,
    try_flush=true) at /Network/Socket.cpp:365
#21 0x00007f9e5c43c13b in toolkit::SocketHelper::send (this=0x7f9e50001e00, buf=std::shared_ptr<class toolkit::Buffer> (empty) = {...})
    at /Network/Socket.cpp:964
#22 0x00007f9e5c43bd44 in toolkit::SockSender::send (this=0x7f9e50001e00, buf=0x7f9e5000ab00 "\003[", size=12)
    at /Network/Socket.cpp:923


我拉的最新master代码，没有多开

**Comment by weibw-720** [comment]
![微信图片_20231227144559](https://github.com/ZLMediaKit/ZLToolKit/assets/58965236/9caa2ee4-92e3-4deb-ba71-a176c449b3b0)

我这是拉取的最新的master代码，没有多开

**Comment by weibw-720** [comment]
![微信截图](https://github.com/ZLMediaKit/ZLToolKit/assets/58965236/e7b8916c-6444-4e3d-9ecb-e722d5767045)
这个问题，我也遇到了，我看之前已关闭的issue中有一个人也遇到了同样问题

**Comment by weibw-720** [comment]
![Uploading 微信图片_20231229160754.png…]()

**Comment by weibw-720** [comment]
![微信图片_20231229160754](https://github.com/ZLMediaKit/ZLToolKit/assets/58965236/1140cc21-f7d9-41ed-89ee-0992f00392b1)
